insert into products (p_name, P_price, p_desc, p_img) values ('Carson', 1978.74, 'Proc/trtmt not crd out bec pt decision for unsp reasons', 'http://dummyimage.com/220x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Trescha', 1920.78, 'Adverse effect of anthelminthics, subsequent encounter', 'http://dummyimage.com/245x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Abrahan', 1375.69, 'Nondisp seg fx shaft of ulna, unsp arm, 7thJ', 'http://dummyimage.com/168x100.png/5fa2dd/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Theodore', 1083.77, 'Ped on foot injured in collision w 2/3-whl mv, unsp, init', 'http://dummyimage.com/102x100.png/ff4444/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Bea', 1838.14, 'Corrosion of second degree of left axilla', 'http://dummyimage.com/149x100.png/dddddd/000000');
insert into products (p_name, P_price, p_desc, p_img) values ('Petra', 1388.22, 'Driver of 3-whl mv injured in clsn w oth mv nontraf, subs', 'http://dummyimage.com/216x100.png/dddddd/000000');
insert into products (p_name, P_price, p_desc, p_img) values ('Zelig', 1201.77, 'Drown due to unpowr wtrcrft overturning, subs', 'http://dummyimage.com/113x100.png/5fa2dd/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Lion', 753.72, 'Displ Maisonneuve''s fx r leg, 7thR', 'http://dummyimage.com/219x100.png/ff4444/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Margot', 1937.78, 'Occls and stenosis of precerb art, not rslt in cereb infrc', 'http://dummyimage.com/174x100.png/dddddd/000000');
insert into products (p_name, P_price, p_desc, p_img) values ('Udall', 995.31, 'Nondisp comminuted fracture of shaft of left femur, init', 'http://dummyimage.com/225x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Wallie', 832.41, 'Nondisp avuls fx (chip fracture) of unsp talus, 7thG', 'http://dummyimage.com/229x100.png/5fa2dd/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Trix', 961.5, 'Prsn outsd pk-up/van inj in nonclsn trnsp acc in traf, init', 'http://dummyimage.com/215x100.png/ff4444/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Alan', 1314.23, 'Contusion of urethra, sequela', 'http://dummyimage.com/132x100.png/5fa2dd/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Brynne', 1627.02, 'Bursopathy, unspecified', 'http://dummyimage.com/126x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Ced', 1647.42, 'Cardiac failure due to anesthesia during pregnancy', 'http://dummyimage.com/117x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Melisent', 873.16, 'Food in respiratory tract, part unsp causing other injury', 'http://dummyimage.com/198x100.png/5fa2dd/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Issi', 1169.84, 'Occup of 3-whl mv injured in clsn w ped/anml in traf, subs', 'http://dummyimage.com/248x100.png/dddddd/000000');
insert into products (p_name, P_price, p_desc, p_img) values ('Ardeen', 996.21, 'Stress fracture, right ankle, initial encounter for fracture', 'http://dummyimage.com/186x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Rora', 1210.19, 'Cerebrovascular disease, unspecified', 'http://dummyimage.com/244x100.png/ff4444/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Zitella', 1081.56, 'Unsp open wound of r little finger w damage to nail, sequela', 'http://dummyimage.com/102x100.png/5fa2dd/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Chery', 1477.38, 'Unspecified open wound of toe without damage to nail', 'http://dummyimage.com/182x100.png/ff4444/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Libbey', 720.48, 'Non-pressure chronic ulcer of other part of foot', 'http://dummyimage.com/196x100.png/dddddd/000000');
insert into products (p_name, P_price, p_desc, p_img) values ('Irving', 804.66, 'Maternal care for intrauterine death, not applicable or unsp', 'http://dummyimage.com/179x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Ingram', 851.6, 'Megaesophagus in Chagas'' disease', 'http://dummyimage.com/133x100.png/ff4444/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Marlin', 1304.78, 'Primary blast injury of sigmoid colon', 'http://dummyimage.com/247x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Kat', 1410.26, 'Path fx in neopltc dis, l ankle, subs for fx w routn heal', 'http://dummyimage.com/187x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Livvyy', 1758.33, 'Disp fx of lunate, unsp wrist, init for clos fx', 'http://dummyimage.com/176x100.png/dddddd/000000');
insert into products (p_name, P_price, p_desc, p_img) values ('Deny', 625.44, 'Toxic effect of unspecified pesticide, assault', 'http://dummyimage.com/104x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Gabi', 828.43, 'Other fracture of fourth metacarpal bone, left hand', 'http://dummyimage.com/239x100.png/dddddd/000000');
insert into products (p_name, P_price, p_desc, p_img) values ('Murdoch', 1919.48, 'Corrosion of second degree of right upper arm, sequela', 'http://dummyimage.com/132x100.png/dddddd/000000');
insert into products (p_name, P_price, p_desc, p_img) values ('Tybi', 1706.35, 'Nondisp fx of proximal phalanx of r thm, init for opn fx', 'http://dummyimage.com/177x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Dud', 794.45, 'Unsp fx r low leg, subs for opn fx type 3A/B/C w nonunion', 'http://dummyimage.com/135x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Lonnie', 1534.76, 'Unspecified complication of heart-lung transplant', 'http://dummyimage.com/190x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Gabriela', 1851.78, 'Oth stimulant abuse w stimulant-induced sexual dysfunction', 'http://dummyimage.com/127x100.png/dddddd/000000');
insert into products (p_name, P_price, p_desc, p_img) values ('Pen', 1768.38, 'Burn of third degree of left wrist, sequela', 'http://dummyimage.com/247x100.png/dddddd/000000');
insert into products (p_name, P_price, p_desc, p_img) values ('Jacquenetta', 527.07, 'Glaucoma secondary to drugs, left eye, moderate stage', 'http://dummyimage.com/236x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Chet', 527.69, 'Poisoning by oth general anesthetics, accidental, sequela', 'http://dummyimage.com/141x100.png/dddddd/000000');
insert into products (p_name, P_price, p_desc, p_img) values ('Fayth', 1890.28, 'Kaschin-Beck disease, vertebrae', 'http://dummyimage.com/187x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Murvyn', 976.49, 'Capslr glaucoma w/pseudxf lens, bilateral, stage unsp', 'http://dummyimage.com/197x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Laurianne', 1447.44, 'Oth complications of the puerperium, NEC', 'http://dummyimage.com/144x100.png/5fa2dd/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Krysta', 1830.1, 'Enteropathic arthropathies, left hip', 'http://dummyimage.com/164x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Jack', 1523.76, 'Laceration of left quadriceps musc/fasc/tend, subs', 'http://dummyimage.com/125x100.png/5fa2dd/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Bamby', 685.87, 'Drowning and submersion due to fall off merchant ship, subs', 'http://dummyimage.com/193x100.png/dddddd/000000');
insert into products (p_name, P_price, p_desc, p_img) values ('Ad', 1607.55, 'Foreign body in uterus', 'http://dummyimage.com/172x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Tammy', 1273.25, 'Burn of second degree of right upper arm, initial encounter', 'http://dummyimage.com/233x100.png/ff4444/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Renado', 1491.36, 'Nondisp commnt fx shaft of r femr, 7thK', 'http://dummyimage.com/112x100.png/dddddd/000000');
insert into products (p_name, P_price, p_desc, p_img) values ('Donnie', 868.17, 'Oth fx shaft of l femr, 7thJ', 'http://dummyimage.com/217x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Ardis', 1942.07, 'Laceration of esophagus (thoracic part), sequela', 'http://dummyimage.com/169x100.png/cc0000/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Shaylah', 1506.74, 'Nondisp fx of l radial styloid pro, 7thD', 'http://dummyimage.com/117x100.png/5fa2dd/ffffff');
insert into products (p_name, P_price, p_desc, p_img) values ('Theodosia', 1314.28, 'Lacerat flexor musc/fasc/tend r mid fngr at forarm lv, init', 'http://dummyimage.com/172x100.png/ff4444/ffffff');